"""Generate a plain-text project documentation file for TestSmith."""

import os
from datetime import date


def generate():
    lines = []
    w = lines.append

    w("=" * 60)
    w("  TESTSMITH — DIAGNOSTIC REPORTING AGENT")
    w("=" * 60)
    w(f"  Generated: {date.today().isoformat()}")
    w("")

    # ── 1. Overview ──
    w("─" * 60)
    w("1. WHAT IS TESTSMITH?")
    w("─" * 60)
    w("")
    w("  TestSmith scans any codebase, runs its existing tests, and produces a")
    w("  structured diagnostic report that identifies coverage gaps, dependency")
    w("  issues, and testability concerns. It is a read-only diagnostic tool —")
    w("  it NEVER writes test files or modifies your code.")
    w("")
    w("  Stack:")
    w("    Backend : FastAPI (async) + SQLAlchemy + SQLite")
    w("    Frontend: React 19 + Vite 6 + Tailwind CSS 4")
    w("    Tests   : pytest + httpx (10 tests)")
    w("")

    # ── 2. Architecture ──
    w("─" * 60)
    w("2. ARCHITECTURE (3 Agents + Orchestrator)")
    w("─" * 60)
    w("")
    w("  +----------+     +----------+     +----------+")
    w("  | SCANNER  | --> |  RUNNER  | --> | ANALYZER |")
    w("  +----------+     +----------+     +----------+")
    w("       |                |                |")
    w("       v                v                v")
    w("   walks repo       runs tests      AST analysis")
    w("   finds files      parses output   markdown report")
    w("")
    w("  Agent       What it does")
    w("  ───────     ─────────────────────────────────────────────")
    w("  Scanner     Walks the repository, finds source & test files by")
    w("              extension (.py, .js, .jsx, .ts, .tsx, .go, .rs,")
    w("              .java, .rb, .php). Detects project type (Python/Node).")
    w("")
    w("  Runner      Copies repo to a temp sandbox, installs dependencies")
    w("              (pip install / npm install), runs pytest or vitest,")
    w("              and parses output for pass/fail/error/skip counts.")
    w("")
    w("  Analyzer    Parses Python source files via AST to extract")
    w("              functions, classes, imports. Detects testability")
    w("              concerns (network calls, file I/O). Generates a")
    w("              markdown diagnostic report with 5 sections.")
    w("")
    w("  Orchestrator (loop.py) runs them sequentially and streams")
    w("  real-time status updates via WebSocket to the frontend.")
    w("")

    # ── 3. Pipeline Flow ──
    w("─" * 60)
    w("3. HOW IT WORKS (End-to-End Flow)")
    w("─" * 60)
    w("")
    w("  1. User submits a local repo path OR a GitHub URL")
    w("     (e.g. https://github.com/user/repo.git)")
    w("  2. If GitHub URL: shallow clone (--depth=1) to temp directory")
    w("  3. Path validated against REPO_ROOT_WHITELIST")
    w("  4. Scanner walks the repo -> produces analysis.json")
    w("  5. Runner copies to sandbox, installs deps, runs tests")
    w("  6. Analyzer reads source files, runs AST analysis")
    w("  7. Final markdown report stored in the database")
    w("  8. All events stream in real-time via WebSocket to the browser")
    w("")
    w("  Status lifecycle: pending -> cloning -> scanning -> running")
    w("                    -> analyzing -> done")
    w("                                    -> dismissed (user action)")
    w("")

    # ── 4. Quick Setup ──
    w("─" * 60)
    w("4. QUICK SETUP")
    w("─" * 60)
    w("")
    w("  Prerequisites: Python 3.12+, Node.js 20+")
    w("")
    w("  Backend:")
    w("    cd backend")
    w("    python3 -m venv venv && source venv/bin/activate")
    w("    pip install -r requirements.txt")
    w("    cp .env.example .env   (or create .env with your settings)")
    w("    uvicorn app.main:app --reload --port 8001")
    w("")
    w("  Frontend:")
    w("    cd frontend")
    w("    npm install")
    w("    npm run dev")
    w("")
    w("  Open http://localhost:5173 in your browser.")
    w("")

    # ── 5. File Layout ──
    w("─" * 60)
    w("5. FILE LAYOUT (Annotated)")
    w("─" * 60)
    w("")
    w("  backend/")
    w("    .env                         Environment variables (gitignored)")
    w("    requirements.txt             Python dependencies")
    w("    pyproject.toml               pytest config")
    w("    app/")
    w("      main.py                    FastAPI app, CORS, lifespan")
    w("      db.py                      SQLAlchemy async engine + session")
    w("      models/run.py              Run ORM model (DB schema)")
    w("      api/runs.py                REST: create/list/view/dismiss runs")
    w("      api/ws.py                  WebSocket for live streaming")
    w("      orchestrator/")
    w("        loop.py                  Pipeline orchestrator")
    w("        scanner.py               Walks repo, finds files")
    w("        runner.py                Runs tests in temp sandbox")
    w("        reporter.py              AST analysis, markdown report")
    w("        prompts/                 System prompt templates")
    w("      mcp_server/tools.py        Standalone MCP tools")
    w("    tests/                       pytest test suite (10 tests)")
    w("")
    w("  frontend/")
    w("    package.json                 Node dependencies")
    w("    vite.config.js               Vite config + proxy")
    w("    index.html                   HTML entry point")
    w("    src/")
    w("      main.jsx                   React entry (StrictMode + Router)")
    w("      App.jsx                    Root: nav header + route defs")
    w("      api/client.js              REST API wrapper (fetch)")
    w("      hooks/useRunSocket.js      WebSocket hook")
    w("      components/")
    w("        AgentStatus.jsx          Status card (idle/working/done)")
    w("        LiveFeed.jsx             Event log display")
    w("      pages/")
    w("        NewRun.jsx               Start a diagnostic run")
    w("        LiveRun.jsx              Real-time dashboard")
    w("        RunDetail.jsx            View report + download/dismiss")
    w("        History.jsx              Past runs list")
    w("")

    # ── 6. API Reference ──
    w("─" * 60)
    w("6. API ENDPOINTS")
    w("─" * 60)
    w("")
    w("  REST (all under /api)")
    w("")
    w("  Method  Path                          Description")
    w("  ──────  ────────────────────────────  ─────────────────────")
    w("  GET     /health                       Health check")
    w("  POST    /runs                         Create a new run")
    w("  GET     /runs                         List all past runs")
    w("  GET     /runs/{id}                    Get run details")
    w("  POST    /runs/{id}/dismiss            Dismiss + cleanup")
    w("")
    w("  Create Run request body:")
    w('    {"repo_path": "/local/path"}  or  {"repo_url": "https://..."}')
    w("")
    w("  List Runs response:")
    w("    [{id, repo_path, repo_url, status, created_at, updated_at}]")
    w("")
    w("  Get Run response includes all fields:")
    w("    analysis, execution_results, report (markdown)")
    w("")
    w("  WebSocket")
    w("")
    w("  Path:    /ws/runs/{run_id}")
    w("  Events (server -> client):")
    w("")
    w("    agent_status  → {agent, status, detail}")
    w("    test_result   → {pass_count, fail_count, error_count, skip}")
    w("    report_ready  → {report: '...markdown...'}")
    w("    run_complete  → {run_id}")
    w("    error         → {detail}")
    w("")

    # ── 7. Frontend Routes ──
    w("─" * 60)
    w("7. FRONTEND ROUTES")
    w("─" * 60)
    w("")
    w("  Path               Page          What it does")
    w("  ────────────────   ─────────    ───────────────────────")
    w("  /                  NewRun        Submit repo path or")
    w("                                   GitHub URL to scan")
    w("  /runs/:id          LiveRun       Real-time streaming with")
    w("                                   agent status cards + log")
    w("  /runs/:id/detail   RunDetail     View report, download .md,")
    w("                                   dismiss run")
    w("  /history           History       List of all past runs")
    w("")
    w("  Navigation: header bar with 'New Run' and 'History' links.")
    w("  Dark theme (bg-zinc-950, accent #8bff4a neon green).")
    w("  Monospace font throughout.")
    w("")

    # ── 8. Environment Variables ──
    w("─" * 60)
    w("8. CONFIGURATION (.env)")
    w("─" * 60)
    w("")
    w("  Variable                Default                       Description")
    w("  ────────                ───────                       ───────────")
    w("  OPENCODE_API_KEY        (empty)                       Key for OpenCode API")
    w("  MODEL                   deepseek-v4                   Model name")
    w("  DB_URL                  sqlite+aiosqlite:///./        SQLite database URL")
    w("                          testsmith.db")
    w("  REPO_ROOT_WHITELIST     *                             Allowed repo roots")
    w("                                                         (comma-separated, * = any)")
    w("  TEST_TIMEOUT_SECONDS    300                           Test execution timeout")
    w("")

    # ── 9. Safety ──
    w("─" * 60)
    w("9. SAFETY & ARCHITECTURAL RULES")
    w("─" * 60)
    w("")
    w("  Non-Negotiable Rules:")
    w("  • Scanner reports only what is observed — no guessing")
    w("  • Analyzer produces reports from actual AST analysis — no invented findings")
    w("  • No test files are generated or written to disk — diagnostic-only")
    w("  • Report writing only through the API — never writes to the target repo")
    w("  • Prompt templates in prompts/ directory — never inlined in code")
    w("")
    w("  Safety Measures:")
    w("  • Repo path validated against whitelist — rejects path traversal (../)")
    w("  • Source file reads capped at 100KB")
    w("  • AST analysis is read-only — never modifies files")
    w("  • Git clone uses --depth=1 (shallow, fast)")
    w("  • Test sandbox cleaned up automatically (shutil.rmtree)")
    w("  • .env gitignored — secrets never committed")
    w("  • Cloned repos cleaned up on dismiss/reject")
    w("")

    # ── 10. Run Model ──
    w("─" * 60)
    w("10. DATABASE MODEL (Run)")
    w("─" * 60)
    w("")
    w("  Field              Type      Description")
    w("  ──────────────     ──────    ─────────────────────────────")
    w("  id                 int       Primary key (auto-increment)")
    w("  repo_path          str       Local path or clone path")
    w("  repo_url           str?      Original GitHub URL (if cloned)")
    w("  clone_path         str?      Temp dir for cloned repo")
    w("  status             str       pending/cloning/scanning/")
    w("                               running/analyzing/done/")
    w("                               dismissed/rejected")
    w("  analysis           JSON      Scanner output")
    w("  execution_results  JSON      Runner output")
    w("  report             Text      Analyzer markdown report")
    w("  transcript         JSON?     Agent conversation log")
    w("  created_at         datetime  Creation timestamp")
    w("  updated_at         datetime  Last update timestamp")
    w("")

    # ── 11. Tests ──
    w("─" * 60)
    w("11. TEST SUITE")
    w("─" * 60)
    w("")
    w("  Run:  cd backend && source venv/bin/activate && pytest -v")
    w("")
    w("  File                Tests")
    w("  ────────────────    ─────────────────────────────────────")
    w("  test_loop.py        Path validation (allowed, blocked, traversal)")
    w("  test_scanner.py     Empty dir, Python project detection")
    w("  test_reporter.py    Empty analysis, report with files")
    w("  test_runner.py      Runner with no project type")
    w("  test_ws.py          Health check, list runs")
    w("")

    # ── Footer ──
    w("=" * 60)
    w("  End of Document")
    w("=" * 60)

    return "\n".join(lines)


def main():
    output_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                               "TestSmith_Documentation.txt")
    content = generate()
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Documentation written to: {output_path}")


if __name__ == "__main__":
    main()
